// Cube: CoachRunCampaign - from T_WEEKLY_RUN_CAMPAIGN (Weekly Run Step 3, level 1 = campaign budgets).
// Every ad campaign attributed to a product (family / Store / Unknown).
cube(`CoachRunCampaign`, {
  sql: `SELECT campaign_id, campaign_name, campaign_type, product, recent_daily_spend, ads_net_60d,
          ads_net_roas_60d, ads_net_roas_1w, ads_net_roas_prev_1w, ads_net_roas_4w,
          multi_product_share, budget_action, current_budget, recommended_budget,
          util_pct, effective_roas, is_new_campaign, coach_mode, strategy_type, days_since_suggestion,
          needs_strategy, current_strategy_id, suggested_family, suggested_strategy, strategy_role, strategy_category, no_coach_decision, age_bucket
        FROM \`onyga-482313.OI.T_WEEKLY_RUN_CAMPAIGN\``,
  refreshKey: { sql: `SELECT MAX(finished_at) FROM \`onyga-482313.OI.LOG_PIPELINE_RUNS\` WHERE procedure_name = 'SP_REFRESH_CUBE_TABLES' AND status = 'OK'` },
  measures: { count: { type: `count` } },
  dimensions: {
    id: { sql: `campaign_id`, type: `string`, primaryKey: true },
    product: { sql: `product`, type: `string` },
    campaignName: { sql: `campaign_name`, type: `string` },
    campaignType: { sql: `campaign_type`, type: `string` },
    recentDailySpend: { sql: `recent_daily_spend`, type: `number` },
    adsNet60d: { sql: `ads_net_60d`, type: `number` },
    adsNetRoas60d: { sql: `ads_net_roas_60d`, type: `number` },
    adsNetRoas1w: { sql: `ads_net_roas_1w`, type: `number` },
    adsNetRoasPrev1w: { sql: `ads_net_roas_prev_1w`, type: `number` },
    adsNetRoas4w: { sql: `ads_net_roas_4w`, type: `number` },
    multiProductShare: { sql: `multi_product_share`, type: `number` },
    budgetAction: { sql: `budget_action`, type: `string` },
    currentBudget: { sql: `current_budget`, type: `number` },
    recommendedBudget: { sql: `recommended_budget`, type: `number` },
    utilPct: { sql: `util_pct`, type: `number` },
    effRoas: { sql: `effective_roas`, type: `number` },
    isNewCampaign: { sql: `is_new_campaign`, type: `boolean` },
    coachMode: { sql: `coach_mode`, type: `string` },
    strategyType: { sql: `strategy_type`, type: `string` },
    // Coverage role (AUTO/EXACT/BROAD/...) — the Weekly Run strategy filter's grain. NOT strategyType,
    // which is the SCALE/MARGIN/CUT bucket.
    strategyRole: { sql: `strategy_role`, type: `string` },
    strategyCategory: { sql: `strategy_category`, type: `string` },
    ageBucket: { sql: `age_bucket`, type: `string` },
    daysSinceSuggestion: { sql: `days_since_suggestion`, type: `number` },
    needsStrategy: { sql: `needs_strategy`, type: `boolean` },
    currentStrategyId: { sql: `current_strategy_id`, type: `string` },
    suggestedFamily: { sql: `suggested_family`, type: `string` },
    suggestedStrategy: { sql: `suggested_strategy`, type: `string` },
    noCoachDecision: { sql: `no_coach_decision`, type: `boolean` },
  },
});
