// Cube: CoachRunKeyword - from T_WEEKLY_RUN_KEYWORD (Weekly Run Step 3, level 2 = keywords per campaign).
// Every coached keyword incl no-action, with a plain reason (why action / why not).
cube(`CoachRunKeyword`, {
  sql: `SELECT keyword_id, campaign_id, parent_name, campaign_name, campaign_type, ad_group_id, targeting, match_type,
          days_since_change, days_since_suggestion, target_cpc,
          w1_clk_day, w1_cpc, w1_roas, w1_units, w4_clk_day, w4_cpc, w4_roas, w4_units, pk_clk_day, pk_cpc, pk_roas, pk_units,
          action, current_bid, recommended_bid, bid_change_pct, reason, is_action, priority_score
        FROM \`onyga-482313.OI.T_WEEKLY_RUN_KEYWORD\``,
  refreshKey: { sql: `SELECT MAX(finished_at) FROM \`onyga-482313.OI.LOG_PIPELINE_RUNS\` WHERE procedure_name = 'SP_REFRESH_CUBE_TABLES' AND status = 'OK'` },
  measures: { count: { type: `count` } },
  dimensions: {
    id: { sql: `keyword_id`, type: `string`, primaryKey: true },
    campaignId: { sql: `campaign_id`, type: `string` },
    parentName: { sql: `parent_name`, type: `string` },
    campaignName: { sql: `campaign_name`, type: `string` },
    campaignType: { sql: `campaign_type`, type: `string` },
    adGroupId: { sql: `ad_group_id`, type: `string` },
    targeting: { sql: `targeting`, type: `string` },
    matchType: { sql: `match_type`, type: `string` },
    daysSinceChange: { sql: `days_since_change`, type: `number` },
    daysSinceSuggestion: { sql: `days_since_suggestion`, type: `number` },
    targetCpc: { sql: `target_cpc`, type: `number` },
    w1ClkDay: { sql: `w1_clk_day`, type: `number` },
    w1Cpc: { sql: `w1_cpc`, type: `number` },
    w1Roas: { sql: `w1_roas`, type: `number` },
    w1Units: { sql: `w1_units`, type: `number` },
    w4ClkDay: { sql: `w4_clk_day`, type: `number` },
    w4Cpc: { sql: `w4_cpc`, type: `number` },
    w4Roas: { sql: `w4_roas`, type: `number` },
    w4Units: { sql: `w4_units`, type: `number` },
    pkClkDay: { sql: `pk_clk_day`, type: `number` },
    pkCpc: { sql: `pk_cpc`, type: `number` },
    pkRoas: { sql: `pk_roas`, type: `number` },
    pkUnits: { sql: `pk_units`, type: `number` },
    action: { sql: `action`, type: `string` },
    currentBid: { sql: `current_bid`, type: `number` },
    recommendedBid: { sql: `recommended_bid`, type: `number` },
    bidChangePct: { sql: `bid_change_pct`, type: `number` },
    reason: { sql: `reason`, type: `string` },
    isAction: { sql: `is_action`, type: `boolean` },
    priorityScore: { sql: `priority_score`, type: `number` },
  },
});
