// Cube: KeywordLift — the 80/20 portfolio + probe rotation for working campaigns (budget > cap),
// from V_KEYWORD_LIFT (live read). Spec: architecture/OOB_BUDGET_PHASE.md §"Lever 2B".
cube(`KeywordLift`, {
  sql: `SELECT campaign_id, campaign_name, channel, budget, in_peak, w_days, campaign_spend_w, loser_share_pct,
               active_probes, keyword_id, ad_group_id, target_text, match_type, is_auto, is_pt,
               current_bid, clicks_w, spend_w, orders_w, roas_w, target_cpc, class,
               probing, CAST(probe_started AS STRING) probe_started, probe_clicks, probe_roas,
               clicks_7d, roas_7d, clicks_8_28, roas_8_28, spend_1d, camp_spend_1d, camp_clicks_7d, camp_roas_7d, camp_clicks_8_28, camp_roas_8_28, clicks_1d, roas_1d, clicks_prev2, roas_prev2, clicks_3d, roas_3d, clicks_4_14, roas_4_14, is_auto_campaign, camp_clicks_3d, camp_roas_3d, camp_clicks_4_14, camp_roas_4_14, camp_clicks_1d, camp_roas_1d, camp_clicks_prev2, camp_roas_prev2, pct_dark, capped, slots, seat_rank, is_defense, is_seasonal, is_research, seasonal_now, role, suggested_budget, budget_reason,
               action, suggested_bid, reason
        FROM \`onyga-482313.OI.V_KEYWORD_LIFT\``,

  // Live-view cube: 15-min TTL (view logic iterates; the orchestration stamp doesn't track it)
  refreshKey: { every: '15 minutes' },
  measures: { count: { type: `count` } },

  dimensions: {
    rowId:        { sql: `CONCAT(campaign_id, '|', COALESCE(keyword_id, target_text))`, type: `string`, primaryKey: true },
    campaignId:   { sql: `campaign_id`,   type: `string` },
    campaignName: { sql: `campaign_name`, type: `string` },
    channel:      { sql: `channel`,       type: `string` },   // 'SP' | 'SB' — bulksheet tab routing
    budget:       { sql: `budget`,        type: `number` },
    inPeak:       { sql: `in_peak`,       type: `boolean` },
    wDays:        { sql: `w_days`,        type: `number` },
    campaignSpendW: { sql: `campaign_spend_w`, type: `number` },
    loserSharePct:  { sql: `loser_share_pct`,  type: `number` },
    activeProbes:   { sql: `active_probes`,    type: `number` },
    keywordId:    { sql: `keyword_id`,    type: `string` },
    adGroupId:    { sql: `ad_group_id`,   type: `string` },
    targetText:   { sql: `target_text`,   type: `string` },
    matchType:    { sql: `match_type`,    type: `string` },
    isAuto:       { sql: `is_auto`,       type: `boolean` },
    isPt:         { sql: `is_pt`,         type: `boolean` },
    currentBid:   { sql: `current_bid`,   type: `number` },
    clicksW:      { sql: `clicks_w`,      type: `number` },
    spendW:       { sql: `spend_w`,       type: `number` },
    ordersW:      { sql: `orders_w`,      type: `number` },
    roasW:        { sql: `roas_w`,        type: `number` },
    targetCpc:    { sql: `target_cpc`,    type: `number` },
    kwClass:      { sql: `class`,         type: `string` },
    probing:      { sql: `probing`,       type: `boolean` },
    probeStarted: { sql: `probe_started`, type: `string` },
    probeClicks:  { sql: `probe_clicks`,  type: `number` },
    probeRoas:    { sql: `probe_roas`,    type: `number` },
    clicks7d:     { sql: `clicks_7d`,     type: `number` },
    roas7d:       { sql: `roas_7d`,       type: `number` },
    clicks828:    { sql: `clicks_8_28`,   type: `number` },
    roas828:      { sql: `roas_8_28`,     type: `number` },
    spend1d:      { sql: `spend_1d`,        type: `number` },
    campSpend1d:  { sql: `camp_spend_1d`,   type: `number` },
    campClicks7d: { sql: `camp_clicks_7d`,  type: `number` },
    campRoas7d:   { sql: `camp_roas_7d`,    type: `number` },
    campClicks828:{ sql: `camp_clicks_8_28`, type: `number` },
    campRoas828:  { sql: `camp_roas_8_28`,   type: `number` },
    clicks1d:     { sql: `clicks_1d`,     type: `number` },
    roas1d:       { sql: `roas_1d`,       type: `number` },
    clicksPrev2:  { sql: `clicks_prev2`,  type: `number` },
    roasPrev2:    { sql: `roas_prev2`,    type: `number` },
    campClicks1d: { sql: `camp_clicks_1d`, type: `number` },
    campRoas1d:   { sql: `camp_roas_1d`,   type: `number` },
    campClicksPrev2: { sql: `camp_clicks_prev2`, type: `number` },
    campRoasPrev2:   { sql: `camp_roas_prev2`,   type: `number` },
    clicks3d:     { sql: `clicks_3d`,     type: `number` },
    roas3d:       { sql: `roas_3d`,       type: `number` },
    clicks414:    { sql: `clicks_4_14`,   type: `number` },
    roas414:      { sql: `roas_4_14`,     type: `number` },
    isAutoCampaign: { sql: `is_auto_campaign`, type: `boolean` },
    campClicks3d: { sql: `camp_clicks_3d`, type: `number` },
    campRoas3d:   { sql: `camp_roas_3d`,   type: `number` },
    campClicks414:{ sql: `camp_clicks_4_14`, type: `number` },
    campRoas414:  { sql: `camp_roas_4_14`,   type: `number` },
    pctDark:      { sql: `pct_dark`,      type: `number` },
    capped:       { sql: `capped`,        type: `boolean` },
    slots:        { sql: `slots`,         type: `number` },
    seatRank:     { sql: `seat_rank`,     type: `number` },
    isDefense:    { sql: `is_defense`,    type: `boolean` },
    isSeasonal:   { sql: `is_seasonal`,   type: `boolean` },
    isResearch:   { sql: `is_research`,   type: `boolean` },
    seasonalNow:  { sql: `seasonal_now`,  type: `boolean` },
    role:         { sql: `role`,          type: `string` },
    suggestedBudget: { sql: `suggested_budget`, type: `number` },
    budgetReason: { sql: `budget_reason`, type: `string` },
    action:       { sql: `action`,        type: `string` },
    suggestedBid: { sql: `suggested_bid`, type: `number` },
    reason:       { sql: `reason`,        type: `string` },
  },
});

