-- Additional keywords for null coverage
INSERT INTO `onyga-482313.OI.DE_PRODUCT_TYPE_KEYWORDS` (keyword, product_type, priority) VALUES

-- ═══ SPANISH TERMS ═══
('regalo', 'Gift Sets', 20),
('regalos', 'Gift Sets', 20),
('regalito', 'Gift Sets', 20),
('caja de regalo', 'Gift Sets', 10),
('cajas', 'Gift Sets', 25),
('caja', 'Gift Sets', 25),
('canasta', 'Gift Sets', 20),
('canastas', 'Gift Sets', 20),
('cesta', 'Gift Sets', 20),
('cestas', 'Gift Sets', 20),
('sorpresa', 'Gift Sets', 20),
('sorpresas', 'Gift Sets', 20),

('juguetes', 'Toys', 15),
('juguete', 'Toys', 15),
('jugetes', 'Toys', 15),
('juego', 'Social Game', 20),
('juegos', 'Social Game', 20),

('diario', 'Journal & Diary', 10),
('diarios', 'Journal & Diary', 10),
('libreta', 'Stationery', 15),
('libretas', 'Stationery', 15),
('cuaderno', 'Stationery', 15),
('cuadernos', 'Stationery', 15),
('papeleria', 'Stationery', 15),
('utiles escolares', 'Stationery', 10),
('marcadores', 'Stationery', 10),
('colores', 'Stationery', 20),
('libros', 'Books', 15),

('maquillaje', 'Beauty', 10),
('perfumes', 'Beauty', 10),
('belleza', 'Beauty', 15),
('crema', 'Beauty', 15),
('cuidado personal', 'Beauty', 10),
('cuidado de la piel', 'Beauty', 10),
('cuidado del pelo', 'Beauty', 10),
('cuidado cabello', 'Beauty', 10),
('colonias', 'Beauty', 15),
('colonia', 'Beauty', 15),

('toalla', 'Bath & Spa', 15),
('toallas', 'Bath & Spa', 15),
('ducha', 'Bath & Spa', 15),
('esponja', 'Bath & Spa', 15),
('esponjas', 'Bath & Spa', 15),

('manualidades', 'Crafts & DIY', 10),
('pintar', 'Crafts & DIY', 15),

('accesorios', 'Accessories', 15),
('llavero', 'Accessories', 10),
('llaveros', 'Accessories', 10),
('diademas', 'Accessories', 10),
('vinchas', 'Accessories', 10),
('bandas', 'Accessories', 15),
('cabello', 'Accessories', 20),

('decoracion', 'Home & Room', 15),
('decoraciones', 'Home & Room', 15),

('fiesta', 'Party Supplies', 15),
('pijamada', 'Party Supplies', 15),
('pijamadas', 'Party Supplies', 15),

('dulces', 'Food & Treats', 10),
('caramelos', 'Food & Treats', 10),

-- ═══ PORTUGUESE TERMS ═══
('brinquedos', 'Toys', 15),
('caderno', 'Stationery', 15),
('menina', 'General', 30),
('meninas', 'General', 30),

-- ═══ COMMON TYPOS / MISSPELLINGS ═══
('joirnal', 'Journal & Diary', 10),
('jornal', 'Journal & Diary', 10),
('jornaling', 'Journal & Diary', 10),
('jurnal', 'Journal & Diary', 10),
('journel', 'Journal & Diary', 10),
('jrenl', 'Journal & Diary', 10),
('hournal', 'Journal & Diary', 10),
('jouenal', 'Journal & Diary', 10),
('jounal', 'Journal & Diary', 10),
('gournal', 'Journal & Diary', 10),
('juernal', 'Journal & Diary', 10),
('diry', 'Journal & Diary', 10),
('direy', 'Journal & Diary', 10),
('direry', 'Journal & Diary', 10),
('diyre', 'Journal & Diary', 10),
('diarys', 'Journal & Diary', 10),
('diery', 'Journal & Diary', 10),
('staionary', 'Stationery', 10),
('stationarry', 'Stationery', 10),
('statinery', 'Stationery', 10),
('stikers', 'Crafts & DIY', 15),
('silme', 'Toys', 10),
('slimes', 'Toys', 10),
('selfcare', 'Beauty', 10),
('bodycare', 'Beauty', 10),
('soa set', 'Bath & Spa', 10),
('trith or dare', 'Social Game', 5),
('troth or dare', 'Social Game', 5),
('truth ir dare', 'Social Game', 5),
('teuth or dare', 'Social Game', 5),
('dare or truth', 'Social Game', 5),

-- ═══ KEYCHAINS / CHARMS ═══
('keychains', 'Accessories', 10),
('key chain', 'Accessories', 10),
('key chains', 'Accessories', 10),
('charms', 'Accessories', 10),
('bag charm', 'Accessories', 10),
('bag charms', 'Accessories', 10),
('backpack charms', 'Accessories', 10),

-- ═══ BRAND NAMES ═══
('happy lolli', 'Gift Sets', 5),
('happylolli', 'Gift Sets', 5),
('happy loli', 'Gift Sets', 5),
('happy lollime', 'Gift Sets', 5),
('lollime', 'Journal & Diary', 5),
('lolli me', 'Journal & Diary', 5),
('lolli', 'Gift Sets', 20),
('lisa frank', 'Stationery', 5),
('hello kitty', 'Accessories', 5),
('hellokitty', 'Accessories', 5),
('sanrio', 'Accessories', 5),
('kuromi', 'Accessories', 5),
('cinnamoroll', 'Accessories', 5),
('my melody', 'Accessories', 5),
('pusheen', 'Accessories', 5),
('stitch', 'Accessories', 5),
('bluey', 'Toys', 5),
('cocomelon', 'Toys', 5),
('aphmau', 'Toys', 5),
('kpop', 'Accessories', 10),
('k pop', 'Accessories', 10),
('bts', 'Accessories', 10),
('taylor swift', 'Accessories', 5),
('sabrina carpenter', 'Accessories', 5),
('victoria secret', 'Beauty', 5),
('claires', 'Accessories', 5),
('clairs', 'Accessories', 5),

-- ═══ SPECIFIC PRODUCTS ═══
('bunny', 'Toys', 20),
('bunnies', 'Toys', 20),
('bunny charm', 'Accessories', 10),
('bunny charms', 'Accessories', 10),
('bunny key chain', 'Accessories', 10),
('bunny keychains', 'Accessories', 10),
('plushies', 'Toys', 10),
('plushy', 'Toys', 10),
('stuffy', 'Toys', 15),
('stuffie', 'Toys', 15),
('stuffies', 'Toys', 15),
('peluche', 'Toys', 10),
('peluches', 'Toys', 10),
('claw machine', 'Toys', 10),
('collage kit', 'Crafts & DIY', 10),
('coloring set', 'Stationery', 10),
('hatchimals', 'Toys', 5),
('little live pets', 'Toys', 5),
('rainbocorns', 'Toys', 5),
('shopkins', 'Toys', 5),
('rainbow high', 'Toys', 5),
('real littles', 'Toys', 5),
('mini verse', 'Toys', 5),
('skillmatics', 'Toys', 5),
('what do you meme', 'Social Game', 5),
('bop it', 'Social Game', 5),
('twister', 'Social Game', 5),
('crazy aaron', 'Toys', 5),
('lite brite', 'Toys', 5),
('junior mints', 'Food & Treats', 5),
('squish mellows', 'Toys', 5),
('nee doh', 'Toys', 5),
('kneedoh', 'Toys', 5),
('needoh', 'Toys', 5),
('rainbow loom', 'Crafts & DIY', 5),
('jellycat', 'Toys', 5),
('moriah elizabeth', 'Crafts & DIY', 5),
('ooly', 'Stationery', 5),

-- ═══ BODY CARE ═══
('body care', 'Beauty', 10),
('body care set', 'Beauty', 5),
('body set', 'Beauty', 10),
('face care', 'Beauty', 10),
('face wash', 'Beauty', 10),
('face routine', 'Beauty', 10),
('skin care kit', 'Beauty', 5),
('hair kit', 'Beauty', 10),
('hair set', 'Beauty', 10),
('pamper', 'Beauty', 15),
('pamper set', 'Beauty', 10),
('pedicure', 'Beauty', 10),
('hygiene', 'Beauty', 15),
('hygiene kit', 'Beauty', 10),
('toiletry', 'Beauty', 15),

-- ═══ MISC CATCH-ALLS ═══
('cute', 'General', 30),
('pink', 'General', 30),
('kawaii', 'General', 25),
('preppy', 'General', 25),
('coquette', 'General', 25),
('aesthetic', 'General', 25),
('girly', 'General', 30),
('fun', 'General', 30),
('luxury', 'General', 30),
('fashion', 'Clothing', 20),
('gymnastics', 'Clothing', 15),
('travel', 'General', 25),
('school', 'Stationery', 25),
('mystery boxes', 'Gift Sets', 10),
('surprise boxes', 'Gift Sets', 10),
('hug', 'Gift Sets', 25),
('hugs', 'Gift Sets', 25),
('bestie', 'General', 30),
('best friend', 'General', 25),
('daughter', 'General', 30),
('adolescente', 'General', 30),
('adolescentes', 'General', 30),
('tweens', 'General', 30),
('teenager', 'General', 30),
('preteens', 'General', 30),
('teens', 'General', 30),
('teenies', 'General', 30),
('unboxing', 'Gift Sets', 20),
('kits', 'General', 25),
('kit', 'General', 25),
('writing kit', 'Stationery', 10),
('writing kits', 'Stationery', 10),
('letter writing', 'Stationery', 10),
('crafting kits', 'Crafts & DIY', 10),
('crafting sets', 'Crafts & DIY', 10),
('hair routine', 'Beauty', 10),
('make up', 'Beauty', 10),
('make up set', 'Beauty', 10),
('kids make up', 'Beauty', 10),
('face sponge', 'Bath & Spa', 10),
('sponge', 'Bath & Spa', 15),
('sponges', 'Bath & Spa', 15),
('piggy bank', 'Home & Room', 10),
('cosas', 'General', 30),
('articulos', 'General', 30),
('detalles', 'General', 30),
('happy', 'General', 30)
;
