import os

PROJECT_ID = os.environ.get('GCP_PROJECT_ID', 'onyga-482313')
DATASET_ID = os.environ.get('BIGQUERY_DATASET', 'OI')

ORDERS_TABLE = f'{PROJECT_ID}.{DATASET_ID}.DE_PURCHASE_ORDERS'
OTHER_PO_TABLE = f'{PROJECT_ID}.{DATASET_ID}.DE_OTHER_PO'
SHIPMENTS_TABLE = f'{PROJECT_ID}.{DATASET_ID}.DE_MANUFACTURER_SHIPMENTS'
SHIPMENT_LINES_TABLE = f'{PROJECT_ID}.{DATASET_ID}.DE_SHIPMENT_LINES'
PAYMENTS_TABLE = f'{PROJECT_ID}.{DATASET_ID}.DE_VENDOR_PAYMENTS'
PRODUCTS_TABLE = f'{PROJECT_ID}.{DATASET_ID}.DIM_PRODUCT'
COSTS_HISTORY_TABLE = f'{PROJECT_ID}.{DATASET_ID}.DIM_COSTS_HISTORY'
ALERTS_TABLE = f'{PROJECT_ID}.{DATASET_ID}.DE_ALERTS'
PHRASE_NEGATIVES_TABLE = f'{PROJECT_ID}.{DATASET_ID}.DE_PRODUCT_PHRASE_NEGATIVES'

BASE_ORDERS = 'DE_PURCHASE_ORDERS'
BASE_OTHER_PO = 'DE_OTHER_PO'
BASE_SHIPMENTS = 'DE_MANUFACTURER_SHIPMENTS'
BASE_SHIPMENT_LINES = 'DE_SHIPMENT_LINES'
BASE_PAYMENTS = 'DE_VENDOR_PAYMENTS'
BASE_PRODUCTS = 'DIM_PRODUCT'
BASE_COSTS_HISTORY = 'DIM_COSTS_HISTORY'
