-- Migration: Add columns to DE_SCHEDULED_SHIPMENTS for single-table approval
-- These columns were previously only in FACT_SHIPMENT_PLAN (SP output).
-- Now the SP writes SUGGESTED rows directly here.

ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS ship_cartons INT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS transit_days INT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS priority INT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS days_until_oos FLOAT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS available_stock INT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS fba_stock INT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS awd_stock INT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS in_transit INT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS demand_window FLOAT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS demand_awd_window FLOAT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS mfr_ready_before INT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS in_production INT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS prior_type_allocations INT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS needs_new_po BOOL;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS new_po_qty INT64;
ALTER TABLE `onyga-482313.OI.DE_SCHEDULED_SHIPMENTS` ADD COLUMN IF NOT EXISTS po_ready_date DATE;
