import type { ResearchRow } from './types';

const num = (v: unknown): number | null => (v == null ? null : Number(v));
const int = (v: unknown): number => (v == null ? 0 : Number(v));

/** Normalize an API row (top-terms or related-terms) into a ResearchRow.
 *  The single place that decides defaults — null for "unknown",
 *  0 only for additive counters. */
export function mapResearchRow(t: Record<string, unknown>): ResearchRow {
  return {
    query_text: String(t.query_text ?? ''),
    match_type: (t.match_type as 'direct' | 'related') ?? 'direct',
    asin_overlap: int(t.asin_overlap),
    total_seed_asins: int(t.total_seed_asins),
    overlap_pct: num(t.overlap_pct),
    weeks_appeared: int(t.weeks_appeared),
    market_impressions: int(t.market_impressions),
    market_clicks: int(t.market_clicks),
    market_purchases: int(t.market_purchases),
    market_cvr_pct: num(t.market_cvr_pct),
    brand_impressions: int(t.brand_impressions),
    brand_clicks: int(t.brand_clicks),
    brand_purchases: int(t.brand_purchases),
    brand_sales: int(t.brand_sales),
    show_rate_pct: num(t.show_rate_pct),
    median_click_price: num(t.median_click_price),
    cost_tier: (t.cost_tier as string) ?? null,
    gender: (t.gender as string) ?? null,
    age_group: (t.age_group as string) ?? null,
    occasion: (t.occasion as string) ?? null,
    holiday: (t.holiday as string) ?? null,
    cpc_12m: num(t.cpc_12m),
    cpc_30d: num(t.cpc_30d),
    product_type: (t.product_type as string) ?? null,
    is_brand_term: Boolean(t.is_brand_term),
    brand: (t.brand as string) ?? null,
    units_cvr_30d: num(t.units_cvr_30d),
    units_cvr_12m: num(t.units_cvr_12m),
    ads_family_orders: int(t.ads_family_orders),
    ads_units_30d: num(t.ads_units_30d),
    ads_units_12m: num(t.ads_units_12m),
    roas_30d: num(t.roas_30d),
    cvr_christmas: num(t.cvr_christmas),
    cvr_easter: num(t.cvr_easter),
    cvr_valentines: num(t.cvr_valentines),
    cvr_graduation: num(t.cvr_graduation),
    cvr_back_to_school: num(t.cvr_back_to_school),
    cvr_mothers_day: num(t.cvr_mothers_day),
    family_purchases: int(t.family_purchases),
    family_clicks: int(t.family_clicks),
    family_impressions: int(t.family_impressions),
    last_week: (t.last_week as string) ?? null,
    weekly_market_impressions: int(t.weekly_market_impressions),
    weekly_market_clicks: int(t.weekly_market_clicks),
    weekly_market_purchases: int(t.weekly_market_purchases),
    weekly_market_cvr_pct: num(t.weekly_market_cvr_pct),
    clicks_median: num(t.clicks_median),
    seg_fit: num(t.seg_fit),
    cps_fit: num(t.cps_fit),
    overall_fit: num(t.overall_fit),
    purchase_rank_score: num(t.purchase_rank_score),
    rank_score: num(t.rank_score),
    ads_purch: num(t.ads_purch),
    ads_cps: num(t.ads_cps),
    est_cps: num(t.est_cps),
    gender_score: num(t.gender_score),
    age_score: num(t.age_score),
    occasion_score: num(t.occasion_score),
    pt_score: num(t.pt_score),
    cps_source: (t.cps_source as ResearchRow['cps_source']) ?? null,
    effective_cps: num(t.effective_cps),
    price_bucket: (t.price_bucket as string) ?? null,
    est_cps_curve: num(t.est_cps_curve),
    intent_factor: num(t.intent_factor),
    is_holiday_active: t.is_holiday_active == null ? null : Boolean(t.is_holiday_active),
  };
}
