-- DE_PLAN_ADS_TARGETS: Monthly ad-spend & CPC targets per family/channel
-- Generated by PlanWizard Step 3 → consumed by Ad Coach
-- Part of the closed-loop ads optimization system
CREATE TABLE IF NOT EXISTS `onyga-482313`.OI.DE_PLAN_ADS_TARGETS (
  -- Key
  family              STRING      NOT NULL,   -- product family (e.g. 'Lollibox')
  yr                  INT64       NOT NULL,   -- target year
  mo                  INT64       NOT NULL,   -- target month (1-12)
  channel             STRING      NOT NULL,   -- 'BRAND' or 'NON_BRAND'

  -- Targets (system-generated inputs for Ad Coach)
  daily_spend_target  FLOAT64,               -- target daily ad spend ($)
  cpc_target          FLOAT64,               -- target cost-per-click ($)

  -- Predicted outcomes (model-calculated)
  predicted_cvr       FLOAT64,               -- predicted conversion rate (fraction)
  predicted_roas      FLOAT64,               -- predicted return on ad spend
  predicted_units     FLOAT64,               -- predicted total units (ads + organic halo)
  predicted_net_profit FLOAT64,              -- predicted net profit ($)

  -- Model parameters used (for audit & recalibration)
  cpc_exponent        FLOAT64,               -- exponent used for CPC scaling
  cvr_exponent        FLOAT64,               -- exponent used for CVR scaling
  ads_share           FLOAT64,               -- ads share fraction used
  season_type         STRING,                -- 'PEAK' or 'OFF'
  multiplier_k        FLOAT64,               -- spend multiplier vs baseline

  -- ROAS reference (frozen at save; helps the coach judge halo + direction)
  ly_ad_net_roas      FLOAT64,               -- ad-only Net ROAS, this channel, 2025 (from V_ADS_CHANNEL_EFFICIENCY)
  cy_ad_net_roas      FLOAT64,               -- ad-only Net ROAS, this channel, 2026
  ly_net_roas         FLOAT64,               -- blended (organic-incl) Net ROAS, family-month, 2025
  cy_net_roas         FLOAT64,               -- blended (organic-incl) Net ROAS, family-month, 2026

  -- Metadata
  plan_strategy_id    STRING,                -- links to DE_PLAN_STRATEGY.id
  created_at          TIMESTAMP   DEFAULT CURRENT_TIMESTAMP(),
  updated_at          TIMESTAMP   DEFAULT CURRENT_TIMESTAMP()
);
